### ISSUE TITLE
akparse fail

### ISSUE THREAD

**Issue by edonyM** [01org/tpm2.0-tools#76] opened 2016-06-28 12:51 UTC
I was trying to test the tpm2.0 tools with `test_all.sh` after it was successfully installed.
I got some error which confuesed me. Which patameter or environment is wrong? It seems to be referred by #8.
```sh
test_tpm2_unseal.sh pass 

EK create succ.. Handle: 0x80000006
EvictControl EK persistent succ.
Flush transient EK succ.

StartAuthSessionWithParams succ.......

Tss2_Sys_PolicySecret succ.......

TPM2_Create succ.......

StartAuthSessionWithParams succ.......

Tss2_Sys_PolicySecret succ.......

Name of loaded key: 
00 0b 97 5c 93 cb fe 8e 58 10 c1 f9 22 75 85 16 
dc 8f b1 02 f1 f3 3d 90 cd 2d ce 03 8f da ee c0 
92 f9 


Loaded key handle:  80000006

EvictControl: Make AK persistent succ.

Flush transient AK succ.
getpubak successfully!
akparse fail, pelase check the environment or parameters!
 test_tpm2_akparse.sh Fail, press any key to continue.... 
```

**Comment by gwei3** [comment] 2016-07-13 09:42
can you please run "tpm2_akparse -f ak_pub.out -k temp.out" under test/ folder and paste the result here?
My result is:
$ tpm2_akparse -f ak_pub.out -k temp.out
file(temp.out) open success.
 write data count: 256, temp.out:
c7 c4 57 f4 d4 73 fb ba 91 52 ae 85 50 36 b8 9f
78 21 af ce 52 1a 41 69 a0 23 b6 e1 34 81 02 5c
cc f8 29 df e9 27 f8 83 25 54 46 64 f8 f7 43 0d
fb c6 2b d7 a4 3e 7c a2 6d f7 42 30 92 f1 b4 51
ce 91 b0 44 a0 50 fb f6 f3 f2 92 3a 12 40 c2 6e
62 b6 fd df cd bf a4 70 95 e4 9b c4 45 30 88 7c
a3 4b 7f 77 c1 b8 9c 12 93 ed aa b9 1a 9e 91 cb
89 01 bc 70 9c 76 c1 05 c8 6f a1 d4 ed cf a3 82
a3 b6 d9 ab 5e 07 bf 66 aa 65 26 db 60 75 43 29
61 21 c2 ea bc ab 10 4f 63 2a 04 b6 e1 8a 64 46
2c 98 f9 52 c0 6c dd 89 50 52 71 c7 1c 34 9a 4e
9d 17 ad 5a 62 45 9b 26 e4 c2 5f 74 e9 9e e6 cf
dd 0a b9 4e 32 61 59 4a ed 7a a2 b0 e6 24 14 92
b0 03 e4 e2 3b 66 18 a6 a4 0b a8 df 69 a6 23 54
bd 86 20 b7 db 96 dc 05 c5 dc 80 cf 94 12 8b f1
49 00 bd 0c 4e 39 c0 9e a4 43 a5 94 dd b8 6b 33

**Comment by edonyM** [comment] 2016-07-14 02:54
I locate that `tpm2_akparse` cannot save key to file in source code file `tpm2_akparse.cpp`. when I add a variable to get the return value from `SaveKeyFile()`, it worked and I don't know why.
```c
int parseAKPublicArea()
{
    TPM2B_PUBLIC outPublic;
    UINT16 size = sizeof(outPublic);
    if( loadDataFromFile(akDataFile, (UINT8 *)&outPublic, &size) )
    {
        return -1;
    }

    /*if( TPM_ALG_RSA == outPublic.t.publicArea.type )
    {
        if(SaveKeyToFile(akKeyFile, TPM_ALG_RSA, outPublic.t.publicArea.unique.rsa.t))
            return -2;
    }*/
    // add tmp to get the return value of SaveKeyToFile()
    if( TPM_ALG_RSA == outPublic.t.publicArea.type )
    {
        int tmp = SaveKeyToFile(akKeyFile, TPM_ALG_RSA, outPublic.t.publicArea.unique.rsa.t);
        if(SaveKeyToFile(akKeyFile, TPM_ALG_RSA, outPublic.t.publicArea.unique.rsa.t))
            return -2;
    }
...
}
```

**Comment by gwei3** [comment] 2016-07-20 23:51
It looks weird...

**Comment by gwei3** [comment] 2016-10-13 18:08
not able to reproduce, close it.

**Closed by gwei3** 2016-10-13 18:08 UTC
