### ISSUE TITLE
TPM error  0xc2800 on tpm2_getpublicak  

### ISSUE THREAD

**Issue by dandantx** [01org/tpm2.0-tools#64] opened 2016-04-21 08:51 UTC
As below,tpm2_getpublicak occur TPM error (0xc2800) during the  load process.**

> 

> tpm2_getpubak -E 0x8101000b -k 0x8101000c -g 0x0001 -D 0x000B -s 0x0014 -f ak_pub.out -n ak_name_pub.out

> StartAuthSessionWithParams succ.......

> Tss2_Sys_PolicySecret succ.......

> TPM2_Create succ.......

> StartAuthSessionWithParams succ.......

> Tss2_Sys_PolicySecret succ.......

>......TPM2_Load Error. TPM Error:0xc2800......

>

**Comment by gwei3** [comment] 2016-04-21 09:40
This is caused by TPM2.0-TSS RM code changes. I raised a PR(https://github.com/01org/TPM2.0-TSS/pull/187) in TPM2.0-TSS for this, but didn't get agreement on that yet.

**Comment by gwei3** [comment] 2016-04-27 07:24
01org/TPM2.0-TSS#187 got merged, and this bug was fixed.

**Closed by gwei3** 2016-04-27 07:24 UTC
Labels: bug
