### ISSUE TITLE
Storing symmetric key which is not generated by TPM

### ISSUE THREAD

**Issue by tkcsndrs** [01org/tpm2.0-tools#311] opened 2017-07-03 08:32 UTC
Hello Support Team,

I would like to use the stack AES-CBC encryption with a symmetric key.
The key will not be generated by the TPM, I just want to store it as a persistent key.
I would need some pointer where to start, 
A. which Tss2_Sys_XXX command I should use from the "tools" for storing the key in NVRAM. 
B. I would also like to know how to clear the persistent key from the NVRAM.

Thank you for the support in advance!
Regards,
andras

**Comment by idesai** [comment] 2017-07-06 19:34
For storing un structured data look at man page examples for  tpm2_nvdefine and tpm2_nvwrite
To erase from memory look at example tpm2_nvrelease

**Comment by tkcsndrs** [comment] 2017-07-07 10:59
Thanks for the pointers! 
One more thing, If I specify an index with -x switch to 0x1500016 (e.g. tpm2_nvdefine -x 0x1500016 etc...) then am I allowed to use this 0x1500016 as a key handle for -k switch of tpm2_encryptdecrypt?  
(e.g. tpm2_encryptdecrypt -k 0x1500016 etc...) OR Should it be converted somehow from index to key handle? Cheers,andras

**Comment by idesai** [comment] 2017-07-07 15:51
I see so you are not just using it for storing the data but to actually use it as a key handle. You should look into Tss2_sys_import

**Comment by williamcroberts** [comment] 2017-07-29 23:58
Duplicate of https://github.com/01org/tpm2.0-tools/issues/218, as we need to implement that tool

**Closed by williamcroberts** 2017-07-29 23:58 UTC
