### ISSUE TITLE
error 0x100

### ISSUE THREAD

**Issue by flihp** [01org/tpm2.0-tools#26] opened 2016-02-08 04:09 UTC
I'm trying to bring the tpm2.0-tools up to speed with the changes that are being made to the sapi code. I got the following error while testing:

    This bank can not be read, tpm error 0x100

Is this a known error? I get this error for the code at the HEAD of the master branch.

**Comment by gwei3** [comment] 2016-02-16 14:31
Which command tool are you using? tpm2-listpcr?

**Comment by flihp** [comment] 2016-02-16 20:10
yup: tpm2-listpcr but the other simple commands that I tried (like getek) returned the same results.

**Comment by wcarthur1** [comment] 2016-02-16 20:18
That error means the TPM hasn’t been initialized.

I suspect that your system’s BIOS or HW doesn’t properly init the TPM.

Will Arthur
Intel Corporation
Server Security Firmware
803-216-2101

**Comment by gwei3** [comment] 2016-02-16 23:30
Run tpmtest before running any tpm2.0-tools command will also cause this issue.

Jimmy

**Comment by gwei3** [comment] 2016-02-18 03:07
this is not a bug. close it.

**Closed by gwei3** 2016-02-18 03:07 UTC
